import os

USERPATH = os.path.expanduser("~")
SYSTEMPATH = "/"
REPOPATH = os.path.expanduser("~/.dotfiles")
REPO_USER_PATH = os.path.join(REPOPATH, "user")
REPO_SYSTEM_PATH = os.path.join(REPOPATH, "system")

DEFAULT_LANGUAGE = "en"
MESSAGES_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "i18n")

README_FIRST_LINE = """<!-- Don't remove this comment. It is used for check if this repo is generated by `dot-cli-py`. You can edit this file as you like but keep this comment as the first line -->"""

print(MESSAGES_PATH)
