import shutil

from rewrite_by_hand.data.variables import REPOPATH
from rewrite_by_hand.core.health import checker, HealthStatus


def cmd_clean(_):
    status = checker.check()
    no_acceptable_status = [
        HealthStatus.Repo_Dir_Path_Not_Exist,
        HealthStatus.Repo_Dir_Path_Exist_But_Is_A_File,
        HealthStatus.Repo_Is_Empty,
        HealthStatus.Repo_Dir_Exist_But_Not_Our_Repo,
    ]
    if status in no_acceptable_status:
        print(f"{REPOPATH} doesn't exist or it's not generated by Dot.")
        return
    else:
        sure = input(
            f"This command will delete your repo {REPOPATH}. Are you sure? (y/n)"
        )
        if sure.lower() != "y":
            print("Aborting clean command.")
            return
        shutil.rmtree(REPOPATH)
        print(f"Cleaned {REPOPATH}")
